function scriptText = custom_genscript(varargin)
    %GENSCRIPT Generate a MATLAB script for running tests.
    scriptText = join([ ...
        "import matlab.unittest.TestRunner;", ...
        "import matlab.unittest.plugins.XMLPlugin;", ...
        "suite = testsuite(pwd, 'IncludingSubfolders', true);", ...
        "testFiles = unique({suite.TestParentName});", ...
        "tempAllFile = tempname;", ...
        "tempSplitFile = tempname;", ...
        "fid = fopen(tempAllFile, 'w');", ...
        "fprintf(fid, '%s\n', testFiles{:});", ...
        "fclose(fid);", ...
        "command = sprintf('circleci tests split --split-by=timings %s 2> %s', tempAllFile, tempSplitFile);", ...
        "[status, stdout] = system(command);", ...
        "suite = testsuite_generation(stdout, tempSplitFile);", ...
        "delete(tempAllFile);", ...
        "delete(tempSplitFile);", ...
        "runner = TestRunner.withTextOutput();", ...
        "runner.addPlugin(XMLPlugin.producingJUnitFormat('results.xml'));", ...
        "results = runner.run(suite);", ...
        "display(results);", ...
        "assertSuccess(results);" ...
    ], newline);

    % Convert to character array 
    scriptText = char(scriptText);
end