function scriptText = custom_genscript(varargin)
    %GENSCRIPT Generate a MATLAB script for running tests.
    
    % Define the script as a single string with newline characters
    scriptText = [...
    "import matlab.unittest.TestRunner;", ...
    newline, ...
    "import matlab.unittest.plugins.XMLPlugin;", ...
    newline, ...
    "cd tests", ...
    newline, ... 
    "tempFile = tempname;", ...
    newline, ... 
    "command = 'circleci tests glob ""**/*.m"" | xargs -n1 basename | sed ''s/\.m$//'' | circleci tests split --split-by=timings 2>' + string(tempFile);", ...
    newline, ...
    "[status, stdout] = system(command);", ... 
    newline, ...
    "cd ..", ...
    newline, ...
    "suite = testsuite_generation(stdout, tempFile);", ...
    newline, ... 
    "delete(tempFile);", ...
    newline, ... 
    "runner = TestRunner.withTextOutput();", ...
    newline, ...
    "runner.addPlugin(XMLPlugin.producingJUnitFormat('results.xml'));", ...
    newline, ... 
    "results = runner.run(suite);", ...
    newline, ...
    "display(results);", ...
    newline, ...
    "assertSuccess(results);"];
    
    % Convert the string array to a single string (if it's not already)
    scriptText = join(scriptText, "");
    
    % Convert to character array if specifically requested to be of char type
    scriptText = char(scriptText);
    
    end